[logging]
level = 'debug'

[paths]
clean_dir = "~/shit/seadge_clean_data"
output_dir = "~/shit/seadge_output"
matfile_dir = "~/uni/p7/ISCLP-KF/param/SQRT_PSD_RETF"
noise_dir = "~/uni/es7_project/audio/clean_noise/normalized"
psd_model = "~/uni/p7/models/cnn_gru/model.pt"

[dsp]
datagen_samplerate = 48000
enhancement_samplerate = 16000
rirconv_xfade_ms = 64
early_tmax_ms = 150
early_offset_ms = 30

[roomgen]
rt60_min = 0.3
rt60_max = 1.0
min_dimensions_m = [3.0, 4.0, 2.0]
max_dimensions_m = [8.0, 10.0, 4.0]
max_image_order = 10

num_generated_rooms = 2
enable_noise = true

min_num_source_locations = 1
max_num_source_locations = 1
# Minimum distances from sources to wall and mic
# Be careful choosing these values since they (along with room dimensions) also determine "spread" of sources in the room
min_source_distance_to_wall_m = 1.0
min_source_distance_to_mic_m = 2.0
min_source_inter_spacing = 0.4
max_source_movement_m = 1.0
max_azimuth_rotation_deg = 90.0

# mic array
num_mics = 5
mic_spacing = 0.05
mic_y = 0.05
mic_z = 1.2

[scenariogen]
scenario_duration_s = 10.0
min_interference_volume = 0.1
max_interference_volume = 0.5
min_snr_db = 10
max_snr_db = 20
scenarios_per_room = 2
